/**
 * Prisma client singleton (PR 1, design.md §10.2).
 *
 * Lambda cold starts must reuse a single PrismaClient per execution
 * environment (a global), not a per-invocation client — otherwise
 * the connection pool fills up and the Lambda hangs.
 *
 * The `connection_limit = 2` setting matches the reserved Lambda
 * concurrency (1) plus a single warm-up slot, which keeps us under
 * the Postgres `max_connections` budget.
 *
 * PR 1 ships the wiring. PR 2a adds the actual schema and the
 * generated Prisma client; this file currently exposes the same
 * surface but uses a typed stub so the build is green today.
 */

import type { ErrorCodeValue } from '@mercadoexpress/shared';

/**
 * The shape every BC expects from a Prisma client. The full type is
 * generated by `prisma generate` in PR 2a; PR 1 ships only the
 * methods the shared middleware uses so the type-check stays green.
 */
export interface PrismaLike {
  $connect(): Promise<void>;
  $disconnect(): Promise<void>;
  $queryRaw(query: string, ...values: unknown[]): Promise<unknown>;
}

export interface PrismaClientOptions {
  /** Maximum simultaneous Postgres connections. Default 2. */
  connectionLimit?: number;
  /** Log levels to emit. Default ['warn', 'error']. */
  log?: Array<'info' | 'warn' | 'error'>;
}

interface GlobalWithPrisma {
  __mercadoExpressPrisma?: PrismaLike;
}

/**
 * Returns a process-singleton Prisma-like client. PR 1 returns a stub
 * so the build is green; PR 2a replaces the body with:
 *
 *   import { PrismaClient } from '@prisma/client';
 *   return new PrismaClient({
 *     log: opts.log ?? ['warn', 'error'],
 *     datasources: { db: { url: process.env.DATABASE_URL } },
 *     // The connection_limit lives in the DATABASE_URL query string,
 *     // e.g. `?connection_limit=2&sslmode=require`.
 *   });
 *
 * The singleton pattern guarantees one client per execution context
 * (warm Lambda keeps the connection pool alive across invocations).
 */
export function getPrismaClient(options: PrismaClientOptions = {}): PrismaLike {
  void options;
  const g = globalThis as GlobalWithPrisma;
  if (!g.__mercadoExpressPrisma) {
    g.__mercadoExpressPrisma = createStubClient();
  }
  return g.__mercadoExpressPrisma;
}

function createStubClient(): PrismaLike {
  // Stub implementation: $connect / $disconnect / $queryRaw return
  // immediately. The real implementation lands in PR 2a.
  return {
    async $connect() {
      /* PR 1 stub */
    },
    async $disconnect() {
      /* PR 1 stub */
    },
    async $queryRaw(_query: string, ..._values: unknown[]) {
      throw new Error('Prisma $queryRaw is a PR 1 stub; generated client ships in PR 2a');
    },
  };
}

/**
 * Type helper for call sites that need to declare a typed Prisma
 * model without importing the generated client. PR 2a will replace
 * the alias with `import { PrismaClient } from '@prisma/client';`.
 */
export type { ErrorCodeValue };
