/**
 * Products BC — CreateProductUseCase (PR 2a).
 *
 * Sequence (products/spec.md "Create product with full validation"):
 *   1. Build a `Product.create(input)` aggregate — the static factory
 *      validates name / sku / price / stock / stockMin / supplier.
 *   2. Validate `categoryId` refers to an existing row.
 *   3. Check SKU uniqueness via `findBySku`. If present, throw
 *      `SkuAlreadyExistsError`.
 *   4. Persist via `ProductRepository.create`.
 */

import { randomUUID } from 'node:crypto';
import { Product } from '../domain/product.js';
import { CategoryNotFoundError } from '../domain/errors/category-not-found.js';
import { SkuAlreadyExistsError } from '../domain/errors/sku-already-exists.js';
import type { ProductRepository } from '../domain/ports/product-repository.js';
import type { CategoryReadRepository } from '../domain/ports/category-repository.js';
import type { AlertOpenerPort } from '../../alerts/domain/ports/alert-opener-port.js';
import type { EmbeddingPort } from '../domain/ports/embedding.js';
import type { Logger as PinoLogger } from 'pino';
import { embedInBackground } from './embed-in-background.js';

export interface CreateProductInput {
  sku: string;
  name: string;
  categoryId: string;
  price: number;
  stock: number;
  stockMin: number;
  supplier: string;
}

export class CreateProductUseCase {
  constructor(
    private readonly products: ProductRepository,
    private readonly categories: CategoryReadRepository,
    private readonly alertOpener: AlertOpenerPort,
    private readonly embedder?: EmbeddingPort,
    private readonly logger?: PinoLogger,
  ) {}

  async execute(input: CreateProductInput): Promise<Product> {
    const aggregate = Product.create({
      id: randomUUID(),
      sku: input.sku,
      name: input.name,
      categoryId: input.categoryId,
      price: input.price,
      stock: input.stock,
      stockMin: input.stockMin,
      supplier: input.supplier,
    });

    const category = await this.categories.findById(aggregate.categoryId);
    if (!category) {
      throw new CategoryNotFoundError(aggregate.categoryId);
    }

    const existing = await this.products.findBySku(aggregate.sku);
    if (existing) {
      throw new SkuAlreadyExistsError(aggregate.sku, existing.id);
    }

    const persisted = await this.products.create({
      id: aggregate.id,
      sku: aggregate.sku,
      name: aggregate.name,
      categoryId: aggregate.categoryId,
      price: aggregate.price,
      stock: aggregate.stock,
      stockMin: aggregate.stockMin,
      supplier: aggregate.supplier,
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    // RF-03 / BR-4: if the product was created with stock below (or equal to)
    // stockMin, open a STOCK_BAJO alert automatically.
    // Best-effort: the product is already committed. If the alert fails for a
    // transient reason (network, timeout — P2002 is already filtered by the
    // adapter), log the error and continue. The alert can be regenerated by a
    // batch job or by re-firing the trigger.
    if (aggregate.stock <= aggregate.stockMin) {
      try {
        await this.alertOpener.openIfAbsent(aggregate.id);
      } catch (e) {
        console.error(
          `[products.create-product] Failed to open STOCK_BAJO alert for product ${aggregate.id} ` +
            `(sku=${aggregate.sku}); product committed without alert:`,
          e,
        );
      }
    }

    // Requirement 7: fire-and-forget embedding after product creation.
    // setImmediate ensures embedding runs after the HTTP response is sent.
    if (this.embedder) {
      const product = Product.rehydrate(persisted);
      const log = this.logger ?? {
        warn: (_meta: object, _msg: string) => {
          /* no-op when no logger injected */
        },
      };
      setImmediate(() => embedInBackground(product, this.embedder!, this.products, log));
    }

    return Product.rehydrate(persisted);
  }
}
